name = "Tabor"
license = "GPL-2.0"
licenselink = "https://github.com/michaelvigor/hugo-theme-tabor/blob/master/LICENSE.md"
description = "A port of the Wordpress Tabor theme to Hugo"
homepage = "https://github.com/michaelvigor/hugo-theme-tabor/"
tags = ["blog"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.74

[author]
  name = "Michael Vigor"
  homepage = "https://michaelvigor.dev"
  twitter = "https://twitter.com/michaelvigor"
